# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Basic Python for Everyone
author: Hayat Khan
logo: logo.png
  

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off
  cache: "" 
  timeout: 100

# The Launch Buttons
launch_buttons:
  colab_url: "https://colab.research.google.com"
  notebook_interface: "jupyterlab"
  binderhub_url: "https://mybinder.org"
  thebe: true
  brannch: main

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/code4geo/pythonic  # Online location of your book
  #path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: "fav.ico"
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true
  use_download_button: true
  thebe: true
  #ignoring the bug report warning
exclude_patterns:
  - .github/ISSUE_TEMPLATE/bug_report.md
  - .github/** 