name: Deploy Jupyter Book to GitHub Pages

on:
  push:
    branches:
      - main  # Change this if your default branch is different

  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        pip install -U pip
        pip install -U jupyter-book myst-parser sphinx-book-theme sphinx-thebe sphinx-comments sphinx-design ghp-import
        pip install jupyter ipython nbconvert

    - name: Build Jupyter Book
      run: jupyter-book build . --builder html

    - name: Deploy to GitHub Pages
      run: |
        ghp-import -n -p -f _build/html
