name: Deploy Jupyter Book to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter-book ghp-import
        pip install -r requirements.txt  # if you have one

    - name: Build book
      run: |
        jupyter-book build --all .
        ls -la _build/html  # Verify build output

    - name: Deploy to GitHub Pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ghp-import -n -p -f _build/html
        echo "Deployment successful!"