name: Deploy Jupyter Book

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Required for git history in ghp-import

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pip'  # Cache dependencies for faster builds

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter-book ghp-import
        pip install -r requirements.txt  # If you have additional requirements

    - name: Build book (with verbose output)
      run: |
        jupyter-book build --all --verbose .
        echo "Build directory contents:"
        ls -la _build/html

    - name: Verify build output
      run: |
        # Check if essential files exist
        [ -f "_build/html/index.html" ] || exit 1
        echo "Build verification passed"

    - name: Deploy to GitHub Pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        ghp-import -n -p -f _build/html
        echo "✔ Successfully deployed to GitHub Pages"

    - name: Post-deployment check
      run: |
        echo "Deployment completed at:"
        date -u
        echo "Your site will be available shortly at:"
        echo "https://<your-github-username>.github.io/<repository-name>/"